### ISSUE TITLE
Enable Laminating in Dimensional Goods

### ISSUE THREAD

**Issue by WMFB** [lairdubois/lairdubois-opencutlist-sketchup-extension#104]
Hi, you have created a brilliant extension and I use it in every one of my woodworking projects. The one **feature** I would love to see is the ability to laminate boards together to create for example a table top. If I have 4 lengths of 25x114 Saligna at 1.2m and wanted to make a table top, OPencutlist could tell me to cut the material in the lengths required and laminate "#'s" to make up the top. I also use this when building cupboards from solid timber, instead of sheet goods.

again thank you for a brilliant product.

regards
Warren

**Comment by bbeaulant** [comment]
Hmm, I'm not sure to understand your needs. Could you explain it with a draw ?

**Comment by WMFB** [comment]
I typically draw the tabletop in one shape as below
[image: image.png]

but I assign it as dimensional lumber, then OCL can then calculate how many
I can laminate side by side to make up the top. as shown below.
[image: image.png]

hope this makes sense.. :)

**Comment by bbeaulant** [comment]
Sorry, but I can't see the image :(

**Comment by WMFB** [comment]
sorry about they, they were png's...

I've added them to a pdf.

**Comment by bbeaulant** [comment]
PNG is not a problem on github comment. But you need to put them on the issue page, not throug email reply maybe.

**Comment by WMFB** [comment]
ahh..... :)

[OCL_Enhancement.pdf](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/3618038/OCL_Enhancement.pdf)

![solid](https://user-images.githubusercontent.com/50667521/64990235-b2bbe900-d8cf-11e9-9327-d5c0192a0284.png)

![planks](https://user-images.githubusercontent.com/50667521/64990248-b7809d00-d8cf-11e9-832a-55e1a79b006a.png)

hope they come through..

**Comment by bbeaulant** [comment]
Ok, I understand :)
But how could this information be presented in the cut list ?

**Comment by WMFB** [comment]
![layout](https://user-images.githubusercontent.com/50667521/65022701-b7b18480-d931-11e9-9f26-f10e0eaf0780.png)
Perhaps something like the sheetgoods, where the laminated parts could be marked A1, for the table tops for example, and B1 could be for the sides... and so on... so the A1's and B1's are grouped/laminated components.

**Comment by CyberBLN** [comment]
Maybe there could be a fifth material type "glued dimensional" that under the hood try to glue a panel from a list of dimensional sizes.

**Comment by bbeaulant** [comment]
@CyberBLN, maybe, but is this enough "general" to cover more use case ?

**Comment by CyberBLN** [comment]
> @CyberBLN, maybe, but is this enough "general" to cover more use case ?

short answer:

No it isn't. Nice to have but not a show stopper.

long answer:

It's a nice feature with a rare use case because you can draw it already in SketchUp before you have to think about the details. So from the user perspective it would be nice to have it if there is a simple to use interface for it.

But from the open source developer perspective (not paid, rare time) I see other topics that have more benefits. For instance generalize the material parameter objects under the hood will save future development time. It's less complicated to read the source code with parameters containing length, width and thickness in their names for the different material types but on the other end it's complicated to extend the Ruby classes and the Twig templates at the moment.

For me (and the saw) any piece of wood have always three dimensions. If it's a panel I'll cut two of them (width and length) and if it's a bar I'll only cut one (length). But for sure I can also cut a bar twice because it's nothing else than a thick and small panel. The main difference is how to define the available sizes (width x length with fixed thickness vs width x thickness with fixed length) but internally it does not matter how the three axises are labeled in the UI.

So I would investigate my time in refactoring and test coverage first before adding new features. The plugin is working stable, have a good and nice user interface and the most common use cases are covered so it can keep as is it for some time.
