### ISSUE TITLE
Cutting Diagram 

### ISSUE THREAD

**Issue by paulwolt** [lairdubois/lairdubois-opencutlist-sketchup-extension#117]
If a component name contains a quote (") then the component is not drawn on the diagram, but is listed below the diagram. For example, component name is «Drawer Side 4" x 12"».

Otherwise Opencutlist is a great help to woodworkers! I love it.

**Comment by bbeaulant** [comment]
Hi @paulwolt,
Thanks for this report, and I'm happy to announce you that this bug was solved in the lastest relsease 1.8.1 (only available [here](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist.rbz), because the extension warehouse is locked until its new version)

**Comment by paulwolt** [comment]
Parfait. Merci.
