### ISSUE TITLE
Can you pls add more How to run this script in local environment?

### ISSUE THREAD

**Issue by ragupathis** [lairdubois/lairdubois-opencutlist-sketchup-extension#123]
In the readme, The information on **how to run a script** is missing. Somewhere I can see **how to set up an environment** . Please help me to run this script in my local environment.

**Comment by bbeaulant** [comment]
Hi,
You just need to load `main.rb`. And this can be done through the [AS On-Demand Ruby Extension](https://alexschreyer.net/projects/plugin-loader-for-sketchup/).

**Comment by ragupathis** [comment]
Hello, Thanks for your response. I tried the above guideline. Unfortunately, It didn't work as expected. I ran a command `ruby main.rb` from the terminal. But I got an error like this 
![Screen Shot 2020-02-11 at 1 32 58 PM](https://user-images.githubusercontent.com/5587483/74219701-95027c80-4cd3-11ea-96d3-e02af95d35bf.png)



Let me elaborate on the scenario, I want to add and edit the textual contents on this plugin. 

Following the above-mentioned blog link, I can't able to load `main.rb` file under the installing new extension section in SketchUp.

**Comment by bbeaulant** [comment]
Hi, all ruby files present in this repository are designed to be lunched in [Sketchup](https://www.sketchup.com) and **only in Sketchup**. You can't run them in terminal because it uses Sketchup API.

There's two way to "run" OpenCutList :
- (PROD env) By installing the *.rbz archive as a "compiled" Sketchup Extension. You can't modify anything.
- (DEV env) By checkout the this reprository and loading the `main.rb` file **in Sketchup**. In this case all resources are loaded from the project folder and you can modify them. But you need to launch the `build --env=dev` gulp command to compile UI or I18N changes.

**Comment by bbeaulant** [comment]
Docs updated : https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/master/docs/01-development.md#6-run-opencutlist-from-dev-project-folder

**Comment by ragupathis** [comment]
Thanks a lot, @bbeaulant , I will check out the links.

**Comment by ragupathis** [comment]
Thanks, mate. It worked.
