### ISSUE TITLE
Additional cut at the bottom and right side which adds saw blade thickness

### ISSUE THREAD

**Issue by JunkyXL86** [lairdubois/lairdubois-opencutlist-sketchup-extension#165]
Version: 1.9.1  DE  ( build: 202007050856 )

When I create the cutting plan there is an unnecessary outer cut on the last pieces towards the bottom and right end of the board. This adds saw blade thickness which leads to pieces not fitting onto the board just because of those missing 2-3 mm.

**Comment by mobilarte** [comment]
I presume your question is about the 2D cutting plan. Could you please provide a simple example showing the problem?

Please consider that there is a length/width oversize defined on the material, making parts larger than what you finally need.  An oversize can also be configured on single parts. There is also a trimming size in the cutting diagram configuration which reduces the size of the panel.

**Comment by JunkyXL86** [comment]
When I generate the cutting plan (2D, yes), OCL splits up the pieces onto two boards.
![first_board](https://user-images.githubusercontent.com/3984217/87207553-69300500-c30c-11ea-8fc8-983fbd538d20.png)
![second_board](https://user-images.githubusercontent.com/3984217/87207573-764cf400-c30c-11ea-972a-12afe8f9e175.png)

When I make the board 3 mm larger, all pieces fit onto a single board. This is just because there is a saw blade margin for this last piece, which in addition exceeds the board size. 

For demonstration purpose I editted the third image to illustrate that the last piece would fit onto the board.
![estimated_single_board](https://user-images.githubusercontent.com/3984217/87207829-363a4100-c30d-11ea-9f69-991bc1e886dd.png)

**Comment by mobilarte** [comment]
Could you please give me the dimensions of all the parts?

This may be a bug, but could also be a consequence of the requirement that all cuts must be guillotine cuts (through-cuts).

**Comment by mobilarte** [comment]
Did you try to configure "length decreasing" instead of the default "width decreasing"?

I tried to reconstruct your problem (may not be exactly the same):

1. width decreasing, one part cannot be placed.

![width_decr](https://user-images.githubusercontent.com/24858423/87289880-87108c00-c4fd-11ea-9d79-f4e1816c6b0e.png)

2. length decreasing, all parts can be placed

![length_decr](https://user-images.githubusercontent.com/24858423/87289909-91328a80-c4fd-11ea-8e4a-56e4c345fd95.png)

**Comment by marguenther** [comment]
I have a similar problem. After the update to 1.9.1 OCL did not create an Cutlist for an existing project. With the "old" Version, same project, same woodlist i could create an cutlist.

I mean the OCL makes unnecessary cuts at the lower edges and therefore not all elements are placed. However, I also have the phenomenon that some elements are placed and there would still be enough space for other parts on the plates, but these are not placed. These are simply not placed at all.

**Comment by mobilarte** [comment]
Thank you for reporting the problem. Can you please give me a concrete example?

**Comment by marguenther** [comment]
Sure.

I have created an table for my table saw. One workplate (there are 2 of the
same size) is about 900x500mm. I want to use an sheet of wood that has an
dimension of 2000mmx500mm. So with 2 cuts there could be those plates cut
out of this sheet. When i create this plate with the right
dimensions (2000mmx500mm) cutlist give me an error: "No placement possible
(side margin too large, standard panel too small, saw cut too large,
...).". If also get this message when i reduce the size of the cut to 0mm.
But if I change the dimension to 2000mmx505mm then OCL create the cutlist
with the unnecessary cut on the lower side.

[image: image.png]


Am Mi., 15. Juli 2020 um 01:16 Uhr schrieb mobilarte <
notifications@github.com>:

**Comment by mobilarte** [comment]
Some parameters add space around your parts or reduce the size of the panel.

1. Did you set the trimming size configuration option of the cutting diagram to 0mm? The trimming size ensures that the sheet has clean and square edges.

<img src="https://user-images.githubusercontent.com/24858423/87511117-155b4e00-c675-11ea-9845-929c326a60bb.png" width="70%">

2. Did you set the general material options for oversizes to 0mm? This option adds some space to each part on the given material to produce rough sizes. Assuming you have the parts roughly cut by a shop and you want to cut them to final dimensions with a cleaner saw blade.

<img src="https://user-images.githubusercontent.com/24858423/87511924-76375600-c676-11ea-854e-72dfea3392c9.png" width="35%">

3. Did you set the part properties oversizes to 0mm? Sometimes a part on a given material needs to be made slightly oversized because it will be fitted when installing it (Küchensockel). This options allows to add some space on a single part, not on all parts of a material.

<img src="https://user-images.githubusercontent.com/24858423/87512129-c57d8680-c676-11ea-9aea-e29588273ae1.png" width="35%">

**Comment by marguenther** [comment]
Yes, i set all part to zero.
1.
![image](https://user-images.githubusercontent.com/827263/87527279-2ebbc480-c68c-11ea-8298-9f8452d36273.png)
This with a width of 505mm. With 500mm i didnt get an cut list.

2.
![image](https://user-images.githubusercontent.com/827263/87527175-0633ca80-c68c-11ea-8596-a509968fee47.png)

3.
![image](https://user-images.githubusercontent.com/827263/87527131-f74d1800-c68b-11ea-8718-90d7ac3db633.png)

**Comment by bbeaulant** [comment]
Strange, @marguenther, could you please mail us your .skp to opencutlist@lairdubois.fr ?

**Comment by marguenther** [comment]
Sure, it's on the way.

Am Mi., 15. Juli 2020 um 11:32 Uhr schrieb Boris Beaulant <
notifications@github.com>:

**Comment by mobilarte** [comment]
Ok, I found the problem by recreating two parts with the dimensions 900mm x 500mm. I made a rectangle and put the dimensions into the VCB:

<img src="https://user-images.githubusercontent.com/24858423/87542618-89144f80-c6a3-11ea-9990-8d6ea20fd354.png" width="30%">

In SketchUp, dimensions are stored internally as decimal inches. Therefore 900mm x 500mm is 35.43307086614173 x
19.68503937007874, but the two original parts have dimensions:

35.43307086614173 x 19.685039370078776, difference is 19.685039370078776 - 19.68503937007874 = 3.5527e-14
35.43307086614173 x 19.685039370078787, difference is 19.685039370078787 - 19.68503937007874 = 4.6185e-14

It is impossible to notice the difference, even if configuring full display precision:

<img src="https://user-images.githubusercontent.com/24858423/87542276-fc699180-c6a2-11ea-91ab-a59f281b3710.png" width="70%">

I do not yet know how and where we will deal with this precision problem.

Thank you!

**Comment by bbeaulant** [comment]
> I do not yet know how and where we will deal with this precision problem.

The problem is that before 1.9.0, dimension were transmitted to cutting diagram algorithm through a string value expressed in model unit and precision reconverted in inch float. But right now the real inch float value is transmitted to cutting diagram computation. Then there no more precision truncation...

Maybe we have to arbitrary truncate float values with the same function used to generate part's IDs.
https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/5f0c25c75fc7c8dafe803aac068f565b073df30f/src/ladb_opencutlist/ruby/utils/dimension_utils.rb#L362

**Comment by mobilarte** [comment]
Since the user cannot see the difference, we should go ahead and implement "what you see is what you get".

**Comment by bbeaulant** [comment]
@marguenther, then you can try the current 1.9.2 DEV release.
https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz

**Comment by marguenther** [comment]
I will try the dev and send an reply. Thank you.

Boris Beaulant <notifications@github.com> schrieb am Mi., 15. Juli 2020,
17:59:

**Comment by mobilarte** [comment]
The fix introduces some weird artifacts

<img src="https://user-images.githubusercontent.com/24858423/87699961-e8528c80-c795-11ea-8a66-eb9233f00b69.png" width="60%">

The 2D algorithm now thinks that it should make a cut at 499.999000, which leads to a cutlength of 2799.99 whereas only a 1000mm cutting is necessary.

**Comment by bbeaulant** [comment]
Arf. You're right !
We may need to discover how Sketchup truncate its values ...

**Comment by bbeaulant** [comment]
Rollback to < 1.9 way to transfert data to cutting diagram lib in last DEV release.
Even if the dimension are not strictly the same. What you see is what you get according to the Sketchup precision parameter.
@mobilarte, 499.999000 is not present anymore :)

**Comment by mgray88** [comment]
I think I'm experiencing this bug as well, but much simpler. I have a sheet good that is defined as having 4'x8' dimensions. Components in the model with full 4'x8' size are not placed in the cutlist. Strangely, even some that are only full size in one dimension are not placed. I have a model I can send where I have reproduced it.

**Comment by bbeaulant** [comment]
@mgray88 as mentioned above, you can send your sample model at <opencutlist@lairdubois.fr>.

**Comment by bbeaulant** [comment]
Ok @mgray88 according of what I can see on the model you send me. Your problem is solved by the 1.9.2 DEV. Link in a comment above.

![Capture d’écran 2020-07-20 à 13 30 01](https://user-images.githubusercontent.com/156056/87933322-53011200-ca8d-11ea-8910-6e00797c2bc5.png)

**Comment by mgray88** [comment]
@bbeaulant I'll give a try later today. Thanks!
