### ISSUE TITLE
Cutlist does not include full length or full width sheet cuts

### ISSUE THREAD

**Issue by mindfullsilence** [lairdubois/lairdubois-opencutlist-sketchup-extension#166]
When only a horizontal or vertical cut is needed, the parts are ignored by the cutlist. For instance, a sheet of plywood is 48" by 96", and I need 3 parts that are 3" by 96". These parts are not placed in the cutting diagram:

<img width="979" alt="Screen Shot 2020-07-12 at 9 25 33 PM" src="https://user-images.githubusercontent.com/1510718/87270847-41fd4300-c486-11ea-991c-5e152dac18db.png">

I believe this is because OpenCutList requires all sides to be cut, but I don't think this should be necessary for the outside edge in a lot of cases. Maybe this should be an option when defining the material?

**Comment by mobilarte** [comment]
This is probably due to the fact that you have the default "trimming size" configured in the cutting diagram configuration tab.
By default we assume that panels need to be trimmed/squared. If you don't care about possible unclean edges, you may set it to zero, in which case a full 96" x 48" part will fit, even if you configured a 2" wide saw blade.

![trimming](https://user-images.githubusercontent.com/24858423/87291586-d6f05280-c4ff-11ea-9c61-8254f0ecfd10.png)

**Comment by mindfullsilence** [comment]
Thanks! Hadn't thought about that. This fixed the issue for the slimmer boards, really appreciate it!
