### ISSUE TITLE
Not including all the parts in one sheet, even though they would fit.

### ISSUE THREAD

**Issue by jecraig** [lairdubois/lairdubois-opencutlist-sketchup-extension#193]
I've got parts that all look like they'll fit (yes it's tight but should work.) It grouped most of the pieces into one group and then put another into a separate group. I can't find any way to get it to group them all together.

![image](https://user-images.githubusercontent.com/20190406/95798051-30f2e680-0cae-11eb-9796-11127097f5b0.png)
![image](https://user-images.githubusercontent.com/20190406/95798115-597ae080-0cae-11eb-8f91-b8ae3876ab99.png)

I've got no trimming size and a 1/8" kerf.

**Comment by bbeaulant** [comment]
Hi @jecraig,

The strange thing in your screenshots, is that you've got 2 parts with the same number "A" and different size...

Else, I just try with your part list and I've got the right result :
![Capture d’écran 2020-10-13 à 07 27 13](https://user-images.githubusercontent.com/156056/95819078-9a620c00-0d25-11eb-9194-88563dca02df.png)

With the following configuration : 
![Capture d’écran 2020-10-13 à 07 28 37](https://user-images.githubusercontent.com/156056/95819217-c5e4f680-0d25-11eb-8792-773861196d52.png)

**Comment by bbeaulant** [comment]
Hi @jecraig,

Thanks for the Sketchup file. Your problem is that **back** part do not do exactly the same thickness than the others.

![Capture d’écran 2020-10-14 à 07 43 39](https://user-images.githubusercontent.com/156056/95948535-02315900-0df1-11eb-9c1b-41bd827d8f82.png)

According to the Sketchup precision, they have the same size. But for various reasons OCL uses the true size of part to order them.

Your best solution is to "redraw" the back part.

**Comment by bbeaulant** [comment]
Try the current 1.9.6-dev build. It may solve your problem.
I change the way to manage length precision.

https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/raw/master/dist/ladb_opencutlist-dev.rbz

**Comment by jecraig** [comment]
The update seems to have worked. All the parts went together in one sheet.

**Comment by bbeaulant** [comment]
Nice :)

**Comment by jlj-ee** [comment]
I was going to open a new issue when I saw this recently-closed issue that seems to match the behavior I am seeing with my model using OCL 1.9.8.

I would expect all the parts to fit on one panel, but OCL is splitting it into two panels:

![image](https://user-images.githubusercontent.com/11401637/97714728-e936d200-1a97-11eb-9e0f-1b56cf0e6a47.png)

![image](https://user-images.githubusercontent.com/11401637/97714807-ffdd2900-1a97-11eb-93bc-fc993f0c00f9.png)

As far as Sketchup can tell me, the thicknesses are the same. I entered the thicknesses of all components manually as 3/4" while modeling. 

Sketchup file attached as well:
[Lummber Cart.zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/5465613/Lummber.Cart.zip)

**Comment by jlj-ee** [comment]
**Update:**
I redrew the troublesome components by explicitly defining the thickness instead of snapping to the dado edges and that seemed to do the trick: 

![image](https://user-images.githubusercontent.com/11401637/97716427-fa80de00-1a99-11eb-99f7-ebf21438bfac.png)
[Lummber Cart (Fixed).zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/5465689/Lummber.Cart.Fixed.zip)


But it is still worth noting that OCL seems to be a little more stringent in its precision/tolerances than the 1/64" precision that I am using on my Sketchup model... which is already a tighter tolerance than I can reasonably expect to cut with most tools! 
Minor issue on an otherwise absolutely fantastic extension. Thanks for all your work!

**Comment by mobilarte** [comment]
I was just going to reply!

You may have noticed that the parts were in two groups in the parts list, even though they seemed to have the same thickness of 3/4".

In the file you sent us, there was no material defined on the Base Frame F/B, Divider and Base Frame L/R. When I added the Wood Plywood Knots, I ended up with the Divider being in a second group. The cutting diagram being calculated per group, you ended up with two sheets.

Try also to play with the cutting diagram Configuration (second tab), width decreasing of the parts and lengthwise stacking may give a cutting diagram that is easier to cut.

**Comment by jlj-ee** [comment]
@mobilarte Thanks for the quick reply! 

You noted that like me, you also ended up with "Divider" in a separate group in the original file I sent. Does that mean OCL is treating it as a different thickness? (Even if the Sketchup precision I am using thinks the thickness is the same as the other group?)

**Comment by mobilarte** [comment]
@jlj-ee 

Yes, the reason for this apparent problem is that SketchUp is using decimal inches as internal units and snaping may result in dimensions that are slightly off, even though you can't see it! 

We have recently changed the way to use the thickness to group parts in [dimension_utils.rb](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/268c99a32c5132a5f6437a26c95c41684d5f5cb5/src/ladb_opencutlist/ruby/utils/dimension_utils.rb), but when debugging problems like yours we have only found that dimensions differ around the 10th decimal position, why? don't know!

**Comment by jlj-ee** [comment]
@mobilarte 
Cool, I appreciate the additional info -- good to know this odd edge case is still on your radar. Thanks for all your help, and apologies for dredging up a closed issue!

**Comment by bbeaulant** [comment]
Hi @jlj-ee, 

Your problem is "normal" as your parts do not have the exact same thickness. Then OCL split them in different groups.

If you switch your model to decimal you will be able to see the difference.

![Capture d’écran 2020-10-30 à 19 07 35](https://user-images.githubusercontent.com/156056/97741777-9125bd00-1ae3-11eb-923d-ad97e75dc119.png)

0.750" vs 0.749"

**OCL works with fixed precision (0.000000)** to determine the thickness of each part. This precision is the max precision of SketchUp.
We do not use the user defined precision because some important ID are generated from part thickness. And, for multiple reasons, it would be better that those IDs stay contant even if the user changes the precision of it's model.

**Comment by jlj-ee** [comment]
@bbeaulant Ah, that's really good to know. With this in mind, I'll switch my setup to decimal to make it easier to catch any thickness discrepancies. Thanks!
