### ISSUE TITLE
Determining the position of part left, right, up, bottom, front and back sides

### ISSUE THREAD

**Issue by agav** [lairdubois/lairdubois-opencutlist-sketchup-extension#221]
Hi, I feel that sides (left, right, up, down) of edge bindings are shown incorrectly. The same applies to the front and bottom sides of model. 

Here is why I think so.

When designing a part I prefer to place my axes manually. I place them to one of the angles and direct red axis along the length and green axis along the width (as it is required by plugin). 
![image](https://user-images.githubusercontent.com/668614/100902174-52fa2f80-34cd-11eb-85ab-cd899b0f2014.png)

I add materials, edge bindings and sometimes additional details not relevant for plugin - e.g. some drillings
I enter the component and align view with red or green axis  (right mouse click on axis)
![image](https://user-images.githubusercontent.com/668614/100902928-082ce780-34ce-11eb-8409-f05e1f501566.png)

It allows me to see the detail from top, and I always understand where texture goes and where is my edge bindings.
![image](https://user-images.githubusercontent.com/668614/100903281-61951680-34ce-11eb-8cab-8dc4e49f6362.png)
(In this example edge binding is on the down side on the view, and I see front side of the detail)

I expect to see the very same positioning of detail in plugin's "part properties" section  but instead I see it differently
![image](https://user-images.githubusercontent.com/668614/100904124-5e4e5a80-34cf-11eb-929a-8a3e4e1aa757.png)

And if I highlight the part I see that surface which I expect to be front is highlighted as back.
![image](https://user-images.githubusercontent.com/668614/100904309-905fbc80-34cf-11eb-88ba-081a4e667af8.png)

I found such positioning in plugin misleading. What do you think?

**Comment by bbeaulant** [comment]
In OCL, there no mention of top, left, bottom and right for edges. Just length 1, length 2 and width 1 and width 2. Because there no sens to speak about top, left, ... if the part is rotated. And that can be misleading.

The OCL logic is to use the positive Z (or virtual Z) axe direction to determine the front and back of a panel. Face nearest the origin is considered as Front and the other is Back. By definition this could only be arbitrary. But I decided to choose this orientation because in most project Front side in more important than Back side and if user want to orient them, he will certainly think about the front side. Then I think that it was easier to put manualy axes from front side to other, in this case.

In the Part Properties panel, OLC presents Front side. Then with the previous logic, Origin is on top, Red axis goes to right, and Green axis goes to bottom (and blue axis goes to the back of the screen).

As I understand your logic is juste the exact opposite. You you refer more to the 3D "Top view". I don't know if it's a belter logic or not. Each one respond positively to a different need.

**Comment by agav** [comment]
Thank you. 
I got your point. And I agree that choosing a front side is a trade off. As for me there are two disadvantages of your approach:
 1) Hard to orient the part to see the front side ("top view" ).
 2) Origin point is shown in top-left corner, but it is customary on the bottom-left corner (at least I get used to have it there).

What do you think about having this configurable?

**Comment by bbeaulant** [comment]
I think that the chosen logic must be universal to all users. Elst it can be misleading.
I don't know which is the best choice. In previous release it uses the "top view" logic. But in usage I found it difficult to use ...

**Comment by bbeaulant** [comment]
Hi @agav,

After a long brainstorming, in the last 2.0.0 release we have change the front and back face detection. It now correspond to what you expect.
