### ISSUE TITLE
Option to display parts list dimensions in inches only

### ISSUE THREAD

**Issue by TwoFistedJustice** [lairdubois/lairdubois-opencutlist-sketchup-extension#226]
When using imperial and measuring something that is less than an arm span, I typically use inches only. It is generally easier to use simple inches than to keep doing base 12 math in my head. (It's sort of a drag to constantly do the math in my head 'X times 12 plus Y and a fraction'.) And then to keep track of the results in my head.

I haven't found a way to change the parts list dimensions to inches only. If there is a way to have it do that would someone please elucidate me? And if not, consider this a feature request.

**Comment by mobilarte** [comment]
Hi @TwoFistedJustice,

Are you sure you did not select "Architectural Inches" instead of "Fractional Inches" in the Model Info -> Units?
You can change this by clicking the start of the first arrow, it should then display all dimensions (at least length/width) in inches only.

This is what it looks for me! I must agree that displaying "inches" does not give enough information and it even displays "inches" when you select "Engineering Feet".

![Clipboard01](https://user-images.githubusercontent.com/24858423/102028033-57b1c400-3da8-11eb-9281-a9d9ffcc0ab5.jpg)

**Comment by TwoFistedJustice** [comment]
That did the trick @mobilarte! Thanks!
