### ISSUE TITLE
Auto-setting the edge from DC

### ISSUE THREAD

**Issue by osxbs** [lairdubois/lairdubois-opencutlist-sketchup-extension#227]
The OCL should take information about the edge from the model attribute. This is necessary to speed up work with OCL.
I make cabinet furniture, and develop for myself dynamic modules of various kitchen cabinets. All of them consist of separate components, in which, theoretically, one or more attributes for the edge could be set, which would be read by ocl and automatically set the edge in the list of parts. In this case, the edge material will also be created automatically.
Now in picture
<img width="1440" alt="Снимок экрана 2020-12-15 в 22 36 04" src="https://user-images.githubusercontent.com/76057665/102238096-f6b0fa00-3f27-11eb-904c-caf8afb0bc4f.png">
The name of the component attribute can be made either static or set in the OCL settings, which is useful for those who also use their dynamic components.

**Comment by bbeaulant** [comment]
Hi @osxbs,

I understand your need, but as I can see, the logic to capture data that you propose is completely different to the current one that uses material applied on edge's faces.
And that's why in first reflexion I would say : It's not the goal of OpenCutList to grab custom data in custom dynamic component attributes and auto-generate edge band materials.

Currently edge band materiel hold more than just a thickness. In your proposal attribute just offer a tickness value. And from where the other values come from ?

**OCL features must be enough commun to feat most user needs. Unfortunately it can't feat each individual needs perfectly.**

In my mind, the best solution for you would be to write a small plugin that to the job to convert your custom DC attributes to edge materials and apply these on edges faces. Or modify OCL by yourself and add this feature for your own build.

**Comment by osxbs** [comment]
In my components, the edge attributes are conditional, they do not change the geometry of the component itself. This is done in most of the component libraries for kitchen furniture that I know. For this reason, I ask you to add a small function that extracts information about the edge from the component.

**Comment by osxbs** [comment]
This is a popular feature for cabinet furniture, I'm not the only one who wants to see this feature in OCL.

**Comment by bbeaulant** [comment]
> in most of the component libraries for kitchen furniture

Which ones ?

**Comment by osxbs** [comment]
https://redkit.pro 

https://craft-kitchen.ru/ru/

https://m.youtube.com/channel/UCfRw7zgndrrHj_8BmNS4iSA

https://plati.market/itm/dynamic-components-of-kitchen-sections-for-sketchup/2460219

**Comment by bbeaulant** [comment]
Ok, but those plugins do not have their own cut list feature ? Else for what are edge attributes setting up ?

**Comment by osxbs** [comment]
The edge attributes are set up for export in the report, and then processed through microsoft excel. A complex design is obtained. Do you agree?

**Comment by osxbs** [comment]
If it's difficult to add 4 parameters to the settings, to write the name of the edge parameters from the dynamic component there, say yes.

**Comment by bbeaulant** [comment]
Hi,

It's not only difficult to implement. It a totally different way to retrieve data and what edge data expect to contains.
For me it's not the goal of OCL to generate automatically textures on faces from data grabbed on DC.
