### ISSUE TITLE
Feature Request: optimize orientation by part

### ISSUE THREAD

**Issue by slynn1324** [lairdubois/lairdubois-opencutlist-sketchup-extension#288]
Awesome plugin - just a suggestion to make it even better.  When laying out a larger plywood project - the grain direction is essential for the visible faces - and that feature works great to configure the appropriate length/width dimensions to get the correct layout.  However, there are often many smaller internal parts where the grain orientation is insignificant as they are unseen, and material usage could be optimized by rotating these pieces.  It would be awesome if there was a way to indicate that certain parts did not require being oriented to the grain, and if they could be automatically re-oriented to best fit in the material.

Thanks!

**Comment by mobilarte** [comment]
Thank you!

We have already thought about that option and the Bin Packing algorithm can handle it. We have yet not implemented it, because we did not exactly figure out where to put the option in the user interface. Grain orientation is an attribute of material, it would have to overriden on the individual instances. 
Another interesting option would be to be able to layout parts in sequence (horizontally or vertically), so that the grain matches (drawer fronts in Birch Plywood).

These options may never be implemented, but I will leave your request open for now.

**Comment by slynn1324** [comment]
Great ideas.  I managed the continuous grain drawer fronts by just defining a single larger panel, so that was pretty easy to work around.  

For the UI, it feels to me that an attribute on each part to ignore the grain orientation would be a pretty intuitive solution.
