### ISSUE TITLE
CNC versus Table saw cutting

### ISSUE THREAD

**Issue by ziyadsaeed** [lairdubois/lairdubois-opencutlist-sketchup-extension#315]
It would be very beneficial if their was a dedicated table, panel saw cutting diagram. where the panel is divided in ever decreasing smaller size. Where cutting ease is priority and not dense packing. I tried some settings but they give me results that are very confusing to do on a table, panel saw. Here are the examples
Advanced No Preference. The area near DEFVV is very complicated to cut.
![Advanced NOPreference](https://user-images.githubusercontent.com/12503225/127035367-0229c67e-5e15-483d-860d-11d2adafe4e4.png)

Advanced Width wise. The area near RRCD is complicated to cut
![Advanced WidthWise](https://user-images.githubusercontent.com/12503225/127035478-fc5e67f8-a83b-4510-b221-e081f9e00e04.png)

Advanced Length Wise. The area near PVSV is complicated to cut
![Advanced LengthWise](https://user-images.githubusercontent.com/12503225/127035602-64a62839-4a69-4741-b9fc-bb2e3014758a.png)

Any advice on how to get less complicated cutting diagrams for table saw cutting. Also i would like a metric for "Total Number of Cuts" and "Total Length of cut". right now it gives me length of cut per panel. How about a cutting table that gives me step by step instructions on how to make the cuts. like how cutlist optimizer does. 
![cutlistoptimizer](https://user-images.githubusercontent.com/12503225/127036274-7edee8ba-d6b5-4191-ad87-549c10828c62.png)

A feature request for CSV export of the data so i can post that here.

**Comment by mobilarte** [comment]
Hi 

> A feature request for CSV export of the data so i can post that here.

CSV export has been part of OCL since version 1.1.0 (2017-04-14): from the Parts List use the top button "Export".

As to your remarks, the goal of OCL is to minimize the number of panels used, therefore it will place small parts wherever possible, without taking particularly care of the resulting cutting pattern. With the option "Preferred Direction", it will try to stack parts width- or lengthwise, but if those parts can be placed inside of an offcut of a panel, it will break the stacks and disperse the parts.

One has to remember that the _optimal solution_ is different for each user. Some users want to minimize cutting length, others want to minimize the number of sheets used or minimize the effect of having the same parts on different panels, or minimize the number of times a panel has to be rotated.

**Comment by bbeaulant** [comment]
Hi,

> Also i would like a metric for "Total Number of Cuts" and "Total Length of cut". right now it gives me length of cut per panel.

This is on our todo list for the next release :wink:

> How about a cutting table that gives me step by step instructions on how to make the cuts. like how cutlist optimizer does.

I'm curious to know how you use it ?
Because after the first cut the sheet reduce and the table is wrong ...

**Comment by ziyadsaeed** [comment]
i understand people have different choices. Make those choices obvious and add another one specially for table saw cutting. In my examples above can anyone tell me how those complicated cuts can be made on a table saw. If i can't cut them than why use an optimizer?

in cultist optimizer example posted above. the cut table highlights the subpanel and where to make the cut. the table doesn't become wrong. It keeps track of the cuts and the remaining panel size. then shows you which remaining size to pick and make the cut. if you have time try it out https://www.cutlistoptimizer.com/
