### ISSUE TITLE
Sort by width in cutlist

### ISSUE THREAD

**Issue by vic1234** [lairdubois/lairdubois-opencutlist-sketchup-extension#319]
Hi
just discovered this extension looks very good 
after trying it I have one problem the cut list is not optimized (aligned) by width of the parts
you can see it in the first picture  you need too change the cut width too much when similar parts width available
it makes you set cutting width on the table saw  than change it to other and than get back to previous ones 
![OpenCutList](https://user-images.githubusercontent.com/2455975/127563974-1d090f4d-d25f-4062-ad91-3d8f79b77457.png)
 
in the second picture the alignment by width is ok 
![OpenCutList2](https://user-images.githubusercontent.com/2455975/127564033-b9246fca-9003-4f11-a749-ec3817a5e894.png)

Thank you

**Comment by mobilarte** [comment]
Hi Victor,

Thank you!

Yes, there is a lot of room for improvement. I have been thinking about ways to reorder the parts inside of a single sheet, maybe even across sheets. In your example it seems pretty easy, but that situation is rare. In most cases reordering would mean walk down all cuts and rearrange the parts. Currently the parts are not in a data structure that allows easy walking through.

In such situations, I will simply reorder the parts (in my head) when cutting on my panel saw, since I know that I can cut through the entire sheet, starting with the widest part.

But your are absolutely right, it could be improved!
