### ISSUE TITLE
Don't check subcomponents of hardware parts

### ISSUE THREAD

**Issue by ziyadsaeed** [lairdubois/lairdubois-opencutlist-sketchup-extension#421]
For eg I have a ONE drawer slide component and that is made of 3 subsomponents. Opencutlist will say I need 3 drawer slides. Almost all models from 3dwarehouse are components made of subcomponents. 

![Screenshot 2022-08-14 045845](https://user-images.githubusercontent.com/12503225/184537374-6536405d-7689-4b19-962d-64ab644eaa5f.png)

Their should be an option where I select a material as hardware and select not to check it's subcomponents.

**Comment by mobilarte** [comment]
This is a very good idea! We will evaluate the consequences of implementing such a feature.

**Comment by bbeaulant** [comment]
Hi,
One alternative that currently works is to set the '**cut opening**' attribute to **true**, on the 3 sub components. Because OpenCutList ignore this kind of components.

<img width="355" alt="Capture d’écran 2022-08-23 à 15 11 23" src="https://user-images.githubusercontent.com/156056/186166777-7827b373-bc00-4e93-a987-36c6f382a8af.png">
