### ISSUE TITLE
Features in report

### ISSUE THREAD

**Issue by Arthur0612M** [lairdubois/lairdubois-opencutlist-sketchup-extension#435]
Hi,

First of all thanks for this amazing tool. 
I wonder if it is possible to include the cutting diagram in the reports? So that with just a clic we can export the cutting diagram for every material?

For now it seems that we have to generate every diagram from the material and print it one by one.

Thanks!

**Comment by bbeaulant** [comment]
Hi @Arthur0612M ,

I understand your need, but currently it will be complex to implement this kind of feature.

In OpenCutList, printing process is only available because the embeded Chrome HTML renderer permit to print what is displayed.
Then to print something we need to display it in HTML first. And long HTML page can consume a lot of resources and may crash or be slow on poor configuration.

Instead of creating something that is not optimal, we prefer to keep OpenCutList as fluid as possible event if it could be boring to export everythings.

**Comment by Arthur0612M** [comment]
Okay, I understand. Thanks a lot!
