### ISSUE TITLE
Optimisation based on tool

### ISSUE THREAD

**Issue by sam-brett** [lairdubois/lairdubois-opencutlist-sketchup-extension#447]
Hi, this might be niche, but I find myself using a track saw for sheet goods more regularly than the table saw. However, there are some cuts that are fiddly on the track saw without planning. 

For example, this is great as I can cut the thin strips off first using a fence and stop block:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/64466838/207616061-374531fc-8624-4ea1-810a-d3b7945c4a40.png">

This, however, isn't good at all:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/64466838/207616902-04bb6eac-3960-4e3d-9d74-626ff4ab7937.png">

This could be laid out like this instead: 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/64466838/207618985-6a75eed8-f821-4be8-a4db-d35a0e96d998.png">

While this might result in more waste, it is a lot easier to produce. It is possible to get this kind of output when playing with axes ordering, but when a wood has no grain direction, it would be nice if there was a deeper level of optimisation for flipping the orientation

**Comment by mobilarte** [comment]
Hi, You are absolutely right! Some cutting patterns look much better and are easier to saw depending on the saw (panel saw, track saw in particular, where you don't want to rotate the panel too many times and where it is optimal to have all identical parts grouped together). This may however lead to a suboptimal number of panels needed. Not an issue for a large number of panels, but if you have to buy 2 instead of 1, it may be critical.

What you describe is not easy to achieve, because the algorithm would need to optimize multiple goals at the same time: least number of panels, least cutting length, least rotations of parts (and many more), and the user would have to indicate how these criteria have to be weighted.

The option "Preferred Direction" tries to stack parts **lengthwise** if they have the same width or **widthwise** if they have the same length. Sometimes this helps to get nicer cutting patterns. If you have many parts, requiring 3 or more panels, it may be a good solution to try the **Advanced Optimization** Level and **All Possibilities** where lengthwise, widthwise and no preference will be tried for each panel to pack.

**Comment by sam-brett** [comment]
Yeah, it is an incredibly complex problem. Especially when I imagine the users vary from huge outfits with CNCs to hobbyists in sheds. I guess my observations as a hobbyist are:

- there seems to be a preference to leave long strips rather than squarer pieces
- while getting decent efficiency per sheet is important, having a target would be good. For example in one of my projects I get 97% on one sheet and ~40% on the second. but the cuts would be difficult without a CNC or alternating between the track and table saw. If I could set a target of 80-90%, then optimise for simpler cuts
- For the opposite case, if the pieces fit on a single sheet maybe allowing the user to force that.

I appreciate this is a free product, so optimising for this use case might be too niche. It's an awesome product though

**Comment by ziyadsaeed** [comment]
other nesting software allow user to assign priority on what should be optimized. For me as well ease of cutting is much more important than using less sheets. here is options in cutlist fx software where you can assign Primary, secondary and tertiary priorities. \
![image](https://user-images.githubusercontent.com/12503225/222260783-a0e0ea96-9d5a-47f8-8382-f1631bb9054e.png)
