### ISSUE TITLE
Dimensional Lumber Estimation

### ISSUE THREAD

**Issue by cmellard** [lairdubois/lairdubois-opencutlist-sketchup-extension#591]
Hi,

The cut list and efficiency reporting for dimensional timber is great however it requires a pre-selection of a standard length as far as I can tell (even if you have multiple standard lengths defined for the material). Typically I'd look to maximise efficiency by selecting a range of dimensional timber lengths from the timber yard, normally a mixture of 4.8m, 5.4m and 6m for most framing jobs. Would be great if the cut list (and estimate) could calculate the most efficient selection of standard lengths to purchase to maximise efficiency.

Cheers
Chris

**Comment by mobilarte** [comment]
Hi,

Although your request seems reasonable at first sight, it is very difficult to implement. To distinguish between all the possibilities, the user would have to enter additional criteria (price/m for the different lengths, preference when 2 or more solutions exist, ...).

The complexity of the calculation grows significantly without real benefit, because longer lengths tend in general to yield better results with less waste, therefore the shorter choices would never be selected. But one good reason for selecting shorter lengths is lack of transport capacity: the lumber yard may pre-cut beams.

Most companies dealing with dimensional lumber I know use 12m or 13m (depending on the type) timbers (glulam).
