### ISSUE TITLE
2 parts with different materials but same thickness gets grouped together

### ISSUE THREAD

**Issue by mauriciobellon** [lairdubois/lairdubois-opencutlist-sketchup-extension#83]
![image](https://user-images.githubusercontent.com/214334/43326398-27769eb8-918f-11e8-92ed-a8d49b756215.png)

**Comment by bbeaulant** [comment]
Hi Mauricio,

Could you please send a sample skp file. I'm not sure to understand your problem with the screenshot only.
Which component has what material in your sample ?

**Comment by mauriciobellon** [comment]
Hi @bbeaulant,

As asked follows the file that I used for the screenshot. 

You will noticed that we have 3 different materials applied to the components of the sample file. There are 2 of those materials that have the same thickness configured on OpenCutList. When I generate the parts list I get only 2 materials (screenshot). OpenCutList is aggregating both same thickness parts (with different material) as one.

Many thanks

[TesteCut.zip](https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/files/2255323/TesteCut.zip)

**Comment by bbeaulant** [comment]
Ok, thanks for the sample file !

This is not a problem of thinkness. This is because 'MDF Branco TX 18mm' and 'MDF Preto TX 18mm' have the same UUID. Then the plugin confuse them. I don't know why in your file those two materials have the same unique identifier.

How do you create those materials ?

https://github.com/lairdubois/lairdubois-opencutlist-sketchup-extension/blob/54a2995f2f1dbe7f0e4293da2752445ec1f801ca/src/ladb_opencutlist/ruby/model/material_attributes.rb#L73

**Comment by mobilarte** [comment]
This is easy to reproduce.

1. Export a material that has been configured.
2. Change its name in the model
3. Re-import the original material

Then you will have a clash of uuid's because the uuid is not regenerated when importing a material.

**Comment by bbeaulant** [comment]
Hmm ... thank you @mobilarte for your investigations !

**Comment by bbeaulant** [comment]
Imported material now reset their UUID.
a126b657f212955363fa618e81f0ab83acb803e8
