### ISSUE TITLE
Materials in report sometimes not recognized

### ISSUE THREAD

**Issue by ALeilands** [lairdubois/lairdubois-opencutlist-sketchup-extension#86]
When generating a parts list, sometimes pieces with different materials get put under the same material although when generating a parts list for a single panel, the material gets picked up correctly. Here is the sample file: https://www.dropbox.com/s/ulg7ir4gop050mk/opencutlist-sample.skp?dl=0

Steps to reproduce the issue:
1. Generate parts list without any parts selected. All pieces appear to have the same material.
2. Select the darker piece, generate parts list. Now it appears to have a different material.
3. Without any parts selected or with everything selected they again appear to have the same material.

This is a critical issue, do you have any ideas what could be causing this behaviour?

**Comment by bbeaulant** [comment]
Hi,

Your right, this is a bug. The bug comes from the UUID generated on material. Those UUID are used internaly instead of the material names. Material UUID's are stored in material attributes, then in your model or exported **skm** files.
But in the 1.5.1, imported material keep their UUID. Then here the white and gray material have the same UUID.

I release a 1.5.2, that reset imported materials UUID. This release was published for review to Trimble today. It will take some day to be available in the Extension Warehouse.

But you can download it here in the `/dist` folder.

**To resolve your problem**, first, install the new 1.5.2 release. And second you need to export one of your material to *.skm from Materials tab.

![capture d ecran 2018-11-01 a 09 21 04](https://user-images.githubusercontent.com/156056/47841161-fccfd500-ddb8-11e8-9628-43337c2d36eb.png)

And after re-import it from the same tab.

![capture d ecran 2018-11-01 a 09 21 49](https://user-images.githubusercontent.com/156056/47841186-1113d200-ddb9-11e8-9da2-07eb8b4bd06a.png)

Go back to the Part List tab an refresh. Your list should be good !

**Comment by ALeilands** [comment]
Very nice, thank you very much! And thanks for the excellent plugin!
